### ISSUE TITLE
Make the data deletion "smarter"

### ISSUE THREAD

**Issue by BoweFrankema** [slaFFik/BP-Default-Data#5]
Currently when you let the plugin delete data it simply removes all users except the super admin and the same goes for groups/activity data.

It would be nice if it somehow could detect the default data created and only delete that whilst leaving the rest intact. This could be done by maybe adding custom meta fields to groups/members/activity and only deleting entries that have that custom fields.

**Comment by slaFFik** [comment]
Yeah, will definitely do that.

**Comment by espellcaste** [comment]
Never noticed that, but +1 for it!

**Comment by slaFFik** [comment]
Finally I fixed this issue.
Now the importing is WAY more smarter.
